# Generated by Django 5.2.9 on 2025-12-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0010_moderationevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file_caption',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
